"""empty message

Revision ID: 22380f51b8e3
Revises: b52ad655f2f1
Create Date: 2023-05-26 19:00:17.125004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22380f51b8e3'
down_revision = 'b52ad655f2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
