"""empty message

Revision ID: 31539abb61ac
Revises: 22380f51b8e3
Create Date: 2023-05-26 19:18:07.783135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31539abb61ac'
down_revision = '22380f51b8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.DateTime(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
