"""empty message

Revision ID: 3524ba839be4
Revises: 511f1ec15365
Create Date: 2023-05-26 21:06:34.922124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3524ba839be4'
down_revision = '511f1ec15365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
