"""empty message

Revision ID: 511f1ec15365
Revises: 26d9d259c40f
Create Date: 2023-05-26 20:03:17.954615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511f1ec15365'
down_revision = '26d9d259c40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
