"""empty message

Revision ID: 82295b7586fc
Revises: 6977f985eb52
Create Date: 2023-05-23 17:35:03.087346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82295b7586fc'
down_revision = '6977f985eb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('convo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_messages_convo_id_conversations'), 'conversations', ['convo_id'], ['id'])

    with op.batch_alter_table('petphotos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_visit', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_column('last_visit')

    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('petphotos', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_messages_convo_id_conversations'), type_='foreignkey')
        batch_op.drop_column('convo_id')

    # ### end Alembic commands ###
