"""empty message

Revision ID: b52ad655f2f1
Revises: ac5a6c7565a0
Create Date: 2023-05-26 16:52:23.280332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52ad655f2f1'
down_revision = 'ac5a6c7565a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_sub', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['auth_sub'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth_sub')

    # ### end Alembic commands ###
